/*
 * C shim for the GEOS <-> PySHiELD radiation CFFI bridge (Phase 1).
 *
 * Mirrors geos_gtfv3_interface.c: turn the Fortran MPI handle into a C MPI_Comm
 * with MPI_Comm_f2c, then call the CFFI-exported Python trampolines declared in
 * geos_rrtmgp_interface_py.h (generated by `python geos_rrtmgp_interface.py`).
 *
 * The one dtype change from gtFV3: all field arrays are `double *` (R8), not
 * `float *`, because RRTMGP is double precision.
 */

#include <stdio.h>
#include "mpi.h"
#include "geos_rrtmgp_interface_py.h"

void geos_rrtmgp_interface_c_init(
    MPI_Fint comm_f,
    int nx, int ny, int nz, int nhalo, int top_at_1,
    int yy, int mm, int dd, int hh, int mn, int sc, double dt)
{
    MPI_Comm comm_c = MPI_Comm_f2c(comm_f);
    geos_rrtmgp_interface_py_init(
        comm_c,
        nx, ny, nz, nhalo, top_at_1,
        yy, mm, dd, hh, mn, sc, dt);
}

void geos_rrtmgp_interface_c(
    // input scalars
    MPI_Fint comm_f,
    int nx, int ny, int nz, int top_at_1,
    int yy, int mm, int dd, int hh, int mn, int sc,

    // input fields
    double *prsi, double *prsl, double *tlyr, double *tsfc,
    double *qvapor, double *qo3mr, double *co2,
    double *qliquid, double *qice, double *qcld,

    // surface inputs
    double *sfc_tsfc, double *islmsk,

    // outputs
    double *flwu, double *flwd, double *fswu, double *fswd,
    double *flwu_clr, double *flwd_clr, double *fswu_clr, double *fswd_clr,
    double *fswn,
    double *hrtlw, double *hrtsw, double *hrtlw_clr, double *hrtsw_clr)
{
    MPI_Comm comm_c = MPI_Comm_f2c(comm_f);

    geos_rrtmgp_interface_py(
        comm_c,
        nx, ny, nz, top_at_1,
        yy, mm, dd, hh, mn, sc,

        prsi, prsl, tlyr, tsfc,
        qvapor, qo3mr, co2,
        qliquid, qice, qcld,

        sfc_tsfc, islmsk,

        flwu, flwd, fswu, fswd,
        flwu_clr, flwd_clr, fswu_clr, fswd_clr,
        fswn,
        hrtlw, hrtsw, hrtlw_clr, hrtsw_clr);
}

void geos_rrtmgp_interface_c_finalize()
{
    geos_rrtmgp_interface_py_finalize();
}
